ミニオークションサイト機能拡張課題・実装
RYU1030/quelcode-cakephp pull request #1
Opened 2020-06-30 04:22 UTC by RYU1030

2020-07-01 05:01 UTC, RYU1030 commented
CakePHP課題① 下記、3つの機能を実装致しました。
レビューをお願い致します。

1. 商品の詳細情報の欄を付け足す。
2. オークションの出品画像（１枚）を付け足す。
3. オークションの終了時刻のカウントダウンタイマーを付け足す。

2020-07-02 10:39 UTC, himaru-jp requested changes

2020-07-02 10:39 UTC, himaru-jp commented on html/mycakeapp/src/Controller/AuctionController.php
> +					if ($this->Biditems->save($biditem)) {
画像の保存に成功した後、データの保存に失敗した場合、
119行目のエラーが表示されてしまいます。
このifの判定に失敗した場合の処理を追加してください。

2020-07-02 10:39 UTC, himaru-jp commented on html/mycakeapp/src/Controller/AuctionController.php
> +				if (move_uploaded_file($file['tmp_name'], $filePath)) {
画像を保存するフォルダをgitの管理内に入れてください。
また、そのフォルダに保存された画像は管理外にしてください。

.gitignore .gitkeep
等で検索してみてください。

2020-07-02 11:50 UTC, RYU1030 commented on html/mycakeapp/src/Controller/AuctionController.php
> +					if ($this->Biditems->save($biditem)) {
失念しておりました。
ご指摘ありがとうございます。

画像の格納成功後にデータ保存に失敗した場合のメッセージを追加しました。

2020-07-02 13:11 UTC, RYU1030 commented on html/mycakeapp/src/Controller/AuctionController.php
> +				if (move_uploaded_file($file['tmp_name'], $filePath)) {
biditems下にgitignoreファイルを作成し、
画像を管理外に設定しました。

2020-07-02 13:19 UTC, RYU1030 commented
ご指摘事項に対応致しました。
1. 画像の格納成功後にデータ保存に失敗した場合のエラーメッセージを追加しました。
2. biditemsディレクトリ下に、gitignoreを作成し、画像をgit管理外に設定。

2020-07-03 04:37 UTC, piasoratech requested changes
細かい部分ですがコメントをしたので確認をお願いします

2020-07-03 04:37 UTC, piasoratech commented on html/mycakeapp/src/Template/Auction/add.ctp
> +<?= $this->Form->end() ?>
ソースコードの最後は改行で終わるようにしましょう

2020-07-03 04:37 UTC, piasoratech commented on html/mycakeapp/webroot/img/biditems/.gitignore
> +*.png
ここも同様です

2020-07-03 04:52 UTC, RYU1030 commented on html/mycakeapp/src/Template/Auction/add.ctp
> +<?= $this->Form->end() ?>
ご指摘ありがとうございます。
修正致しました。

2020-07-03 04:53 UTC, RYU1030 commented on html/mycakeapp/webroot/img/biditems/.gitignore
> +*.png
同様に、改行を追加しました。

2020-07-03 04:53 UTC, RYU1030 commented
ご指摘に基づき、ソースコードの最後に改行を追加する修正を施しました。

2020-07-03 06:34 UTC, piasoratech approved these changes
OKです！
次に進みましょう

2020-07-03 06:38 UTC, merged